name: Release
on: 
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  test: 
    uses: coolapso/dry/.github/workflows/go_test.yaml@main
    with:
      build: false
  release:
    needs: test
    permissions: 
      contents: write
    uses: coolapso/dry/.github/workflows/release.yaml@main
    secrets: inherit
